[project]
name = "phylojumps"
version = "0.1.0"
description = "Code package for phylojumps"
readme = "README.md"
requires-python = ">=3.9,<3.12"
license = { text = "GPL" }

authors = [
    { name = "Steven Nguyen", email = "steven.n.1618@gmail.com" },
    { name = "Hanxi Sun", email = "hanxi.sun.work@gmail.com" },
    { name = "Vinayak Rao", email = "varao@purdue.edu" },
    { name = "Heejung Shim", email = "heejung.shim@unimelb.edu.au" },
]

maintainers = [
    { name = "Steven Nguyen", email = "steven.n.1618@gmail.com" },
]

dependencies = [
    "numpy~=1.23.0",
    "ete3~=3.1.2",
    "pandas~=1.4.4",
    "tqdm~=4.64.1",
    "scipy~=1.9.1",
    "seaborn~=0.11.2",
    "PyQt5~=5.15.7",
    "pyarrow~=16.1.0",
    "matplotlib~=3.7.5",
    "pydantic>=2.13.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/treeHPYPcts"]
